### ISSUE TITLE
Hidden mode (no console shown)

### ISSUE THREAD

**Issue by marysiamzawka** [hugopilot/fl-studio-discord-rpc#5]
It's a pet peeve of mine, but I think the console window is really unnecessary unless you want to do debugging. There should be an option to hide it from the tray at least.

**Comment by showengineer** [comment]
Sorry for not being able to fix this quickly. I didn't have the time lately. I created a GUI, which launches in system tray and it will be included in [v0.1-b2](https://github.com/hugopilot/fl-studio-discord-rpc/releases/tag/v0.1-b2). Let me know if it was fixed for you!
