### ISSUE TITLE
Windows Security marks RPC_Setup.exe as Trojan

### ISSUE THREAD

**Issue by JohnBoyDev** [hugopilot/fl-studio-discord-rpc#6]
Hi, I tried to download your executable, but Windows Security marked it as a Trojan.

![image](https://user-images.githubusercontent.com/12014221/68100441-ae528c00-fe8d-11e9-895d-eaa9223ba1f8.png)

**Comment by showengineer** [comment]
Hi. Thanks for reporting.

Interesting to see that Windows Defender thinks it's a trojan, while it's actually just an installer. [See the VirusTotal report on the setup file](https://www.virustotal.com/gui/file/a8efc79bf2821d59c248b9e4a7838bb425e0478a02acf392d4f4b2b320461e61/detection). I would recommend to let the anti-virus ignore the file. I fully scanned my PC regarding this issue to see if Fuery would be present, but nothing was found.

**Comment by showengineer** [comment]
You can always, if you wish, compile the project yourself
