### ISSUE TITLE
403 Forbidden?

### ISSUE THREAD

**Issue by techboy04** [hugopilot/fl-studio-discord-rpc#8]
Hello!
So I followed the instructions and it seemed to work perfectly
But for some reason the file name is shown as 403 Forbidden and not the actual file name.
![image](https://user-images.githubusercontent.com/26682382/92410429-05f6ff00-f112-11ea-8ab5-bf68bbc55daf.png)

Anyone know a fix?

**Comment by showengineer** [comment]
Hah, that's the default message in 'secret mode'. You can change it by accessing the settings.

**Comment by showengineer** [comment]
![image](https://user-images.githubusercontent.com/10338882/92412044-9f420780-f14a-11ea-80ad-d4ad113e781c.png)
Right-Click, then options. Toggle secret mode if you want it disabled. The secret message content can be modified if you access settings.

**Comment by techboy04** [comment]
Oh didnt realize I was at that setting LMAO. Thank you

**Comment by joaisa17** [comment]
> Hah, that's the default message in 'secret mode'. You can change it by accessing the settings.

Might want to include that in the readme
