### ISSUE TITLE
Failed to save settings - Access to settings.xml is denied

### ISSUE THREAD

**Issue by joaisa17** [hugopilot/fl-studio-discord-rpc#9]
When attempting to change the settings for the RPC, I encountered an issue stating that the app didn't have access to change the settings.xml file. I had to manually edit the file by opening a program as admin, and changing the XML.

![Error message](https://user-images.githubusercontent.com/89845084/159173358-c9c5aa25-9081-44e3-9e12-75d48756a0f2.png)

**Comment by showengineer** [comment]
Probably the installer not setting proper perms during installation, I guess?

**Comment by demberto** [comment]
@0x2b00b1e5 You should store user preferences in one of the `AppData/Roaming` or `AppData/Local` folders. Permission issues won't be caused at all

**Comment by LunaaTheFur** [comment]
Know I'm a bit late to this, but go into C:\Program Files (x86)\fl-studio-rpc\Release and run the FLRPC-GUI.exe as administrator. it'll work just fine when ran as an administrator 👍

**Comment by SinusQuell** [comment]
You can also just adjust the permissions on the "fl-studio-rpc" folder, so the tool can run it without admin permissions, if you're not comfy with that.

**Comment by showengineer** [comment]
This should be fixed. Preferences should be saved in AppData as @demberto said, but I am dropping this project unfortunately. Feel free to fork and fix.
